x-app-image: &app-image registry.gcp
x-app-volumes: &app-volumes
  - type: bind
    source: ./files/pkl/gpd_greater_bdg.pkl
    target: /app/files/pkl/gpd_greater_bdg.pkl
    read_only: true

version: '3.7'
services:
  api:
    image: *app-image
    restart: unless-stopped
    ports:
      - 8080:8501
    env_file:
      - .env
    volumes: *app-volumes
